### ISSUE TITLE
how do i build electrum-git

### ISSUE THREAD

**Issue by leshow** [atweiden/pkgbuilds#1]
You have a pkgbuild for electrum-git, but how do i use the setup.py and electrum.install you have?

**Comment by atweiden** [comment]
```
$ git clone https://github.com/atweiden/pkgbuilds --depth=1
$ cd pkgbuilds/electrum-git
$ makepkg -Acsi
```

**Comment by leshow** [comment]
do you have any plans to adopt the electrum-git package in the AUR? it seems as thought the maintainer is no longer updating it. 

https://aur.archlinux.org/packages/electrum-git/

**Comment by atweiden** [comment]
I wouldn't mind taking it over, but it's up to RunningDroid.

**Comment by leshow** [comment]
would you mind re-adding/updating your pkgbuild for sx-git and it's deps to the AUR? I sorely miss that package

**Comment by atweiden** [comment]
sx has been deprecated in favor of [libbitcoin-explorer](https://aur.archlinux.org/packages/libbitcoin-explorer-git/)

**Comment by leshow** [comment]
Unfortunately that fails to build as libbitcoin-git fails to build, I've submitted an issue with the libbitcoin guys
